OrdererOrgs:
- Name: Orderer
  Domain: agiletech.vn
  Specs:
  - Hostname: orderer0
  - Hostname: orderer1
PeerOrgs:
- Name: Org1
  Domain: org1.agiletech.vn
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Org2
  Domain: org2.agiletech.vn
  Template:
    Count: 1
  Users:
    Count: 1
