version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger-ov
services:
  peer0_org1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: peer0.org1.agiletech.vn
    image: hyperledger/fabric-peer:x86_64-1.1.0-preview
    networks:
      hyperledger-ov:
        aliases:
        - peer0.org1.agiletech.vn
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org1.agiletech.vn
    - CORE_PEER_ADDRESS=peer0.org1.agiletech.vn:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.agiletech.vn:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-ov
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.agiletech.vn:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/org1.agiletech.vn/peers/peer0.org1.agiletech.vn/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/org1.agiletech.vn/peers/peer0.org1.agiletech.vn/tls:/etc/hyperledger/fabric/tls
  peer0_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: peer0.org2.agiletech.vn
    image: hyperledger/fabric-peer:x86_64-1.1.0-preview
    networks:
      hyperledger-ov:
        aliases:
        - peer0.org2.agiletech.vn
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org2.agiletech.vn
    - CORE_PEER_ADDRESS=peer0.org2.agiletech.vn:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.agiletech.vn:7051
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-ov
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.agiletech.vn:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/org2.agiletech.vn/peers/peer0.org2.agiletech.vn/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/org2.agiletech.vn/peers/peer0.org2.agiletech.vn/tls:/etc/hyperledger/fabric/tls
