kind: PersistentVolume
apiVersion: v1
metadata:
  name: org2peer1-pv
  labels:
    type: local
    name: org2peer1files
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/org2peer1/var
    server: storage.local.parisi.biz
    readOnly: false
