kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: org1peer0-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: org1peer0files
