apiVersion: v1
kind: Service
metadata:
  name: example-org2peer0
  labels:
    run: example-org2peer0
spec:
  type: ClusterIP
  selector:
    name: org2peer0
  ports:
    - protocol: TCP
      port: 30110
      name: grpc
    - protocol: TCP
      port: 30111
      name: events
